# Generated by Django 3.2.5 on 2021-07-31 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 16, 23, 28, 914436, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='post',
            table='articels',
        ),
    ]
